### ISSUE TITLE
Update browse imagery to be masked, have color

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/disp-s1#137]
- Mask browse imagery based on conncomps/bad pixel mask/water mask
- Add color instead of grayscale

**Comment by scottstanie** [comment]
@gracebato do you have a request for the colormap?

**Comment by gracebato** [comment]
@scottstanie I would think the jet colormap is fine for default color (I personally prefer this for my own use case) but something to consider would be https://cmap-docs.readthedocs.io/en/latest/catalog/diverging/crameri:vik/ for colorblind. Also for both cases, could we use: towards red as inflation/uplift (basically positive) and towards blue as deflation/subsidence (negative)? This is what's more important if I am putting myself in an end-user perspective, i.e., on how colors can be associated with the ground movement.

**Comment by scottstanie** [comment]
for an example v0.6 product for short_wavelength_displacement:

![image](https://github.com/user-attachments/assets/79616122-e743-46b6-a145-8e6e808eef82)

- default colormap is `RdBu_r` (negative == away from satellite is blue, positive == toward the satellite is red)
- default limits are (-15, 15)

i made this on an existing .nc file by running 
```python
disp-s1 make-browse -i ~/Downloads/OPERA_L3_DISP-S1_IW_F09157_VV_20160705T020730Z_20170823T020701Z_v0.4_20240918T020617Z.nc -o test-browse.png
```

@mirzaees @gracebato
